version: '3.5'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - '8000:8000'
    command: gunicorn -b 0.0.0.0:8000 project:app
    volumes:
      - .:/usr/src/app
