version: '3.5'

services:
  server:
    build: ./project
    image: server
    container_name: server
    ports:
      - '8000:8000'
    volumes:
      - './project/app/:/usr/src/app'
    command: gunicorn -b 0.0.0.0:8000 server:app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  celery:
    image: server
    volumes:
      - './project/app/:/usr/src/app'
      - './project/logs:/logs'
    command: celery -A server.tasks worker --loglevel=info --logfile=/logs/celery.log -c 1
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - server
      - redis

  redis:
    image: redis:3.2.11

  monitor:
    image: server
    volumes:
      - './project/app/:/usr/src/app'
    ports:
      - '5555:5555'
    command:  flower -A server.tasks --port=5555 --broker=redis://redis:6379/0 
    depends_on:
      - server
      - redis
